vitobotta/hetzner-k3s

lib/hetzner/k3s/cli.rb

First of all, thank you for your wonderful piece of software!
When I want to use an "older" release of k3s (eg.: 1.20.12 which was released two weeks ago) I get the following error:
```
Some information in the configuration file requires your attention:
- Invalid k3s version
```
I find this part of the code:
https://github.com/vitobotta/hetzner-k3s/blob/f2154e59d7baaaedd16d506a2bc11b294e3b08f7/lib/hetzner/k3s/cli.rb#L201
It uses GitHub API to search for tags, but it will only send back the last 30 tags.
According to GH API [docs](https://docs.github.com/en/rest/reference/git#references), it's possible to increase the page size, using the `per_page` parameter.
So I raised this per_page limit to 999.

Use larger page size while validating k3s version

---

src/kubernetes/installer.cr

I discovered a bug with the new arm servers, as the csi-driver docker image tagged with 'latest' is not compatible with arm. https://hub.docker.com/r/hetznercloud/hcloud-csi-driver/tags?page=1
I pinned the version to 2.3.2 which is compatible with arm.
Have tested it in my cluster and now the image gets pulled.

Added arm fix with pinned version

---

src/hetzner/client.cr
src/hetzner/server/find.cr

Fixes return lists without the actual server when more than 25 entries.

Using server name to reduce return list. fixes vitobotta/hetzner-k3s#184

---

src/hetzner/load_balancer.cr
src/kubernetes/installer.cr

Add the private IP of the load balancer to the certificate of the k8s API server.
See https://github.com/vitobotta/hetzner-k3s/issues/238
Tested by creating a single master cluster: OK 
Tested by creating a 3 master cluster: openssl s_client --showcerts shows the SAN of the private IP had been added.

private IP of LB in san of k8s api

---

templates/cluster_autoscaler.yaml

The arm64 machines on Hetzner require cluster-autoscaler v1.27.1 onwards. Prior to that, the wrong architecture is sent to the API and the request fails.

Bump cluster-autoscaler to v1.27.3

---

README.md
src/configuration/main.cr
src/kubernetes/installer.cr

`api_server_dns` setting to support alternate DNS for k8s API server. 
See issue https://github.com/vitobotta/hetzner-k3s/issues/238

api_server_dns setting to support alternate DNS for k8s API server

---

cluster_config.yaml.example
src/configuration/main.cr

The PR updates the manifest files to point to latest CSI and CCM versions.
CSI Driver 2.4.0 on 2023-08-25
Cloud controller manager v1.18.0 on 2023-09-18

Update version numbers for CSI and CCM manifests.

---

README.md
cluster_config.yaml.example
src/configuration/main.cr
src/kubernetes/installer.cr
templates/master_install_script.sh

This PR adds three new options to the configuration:
- `cluster_cidr`
- `service_cidr`
- `cluster_dns`
These three options are basically just passed on to the CLI command when setting up the master.
I have compiled and tested it with a small test cluster on Hetzner. Everything seems to work.
**Please note:** This is the first time that I work with Crystal. I haven't really heard of this language before I've seen this project. So if anything is wrong, please tell me so I can fix it (and learn).

Add configuration options for cluster-cidr, service-cidr and cluster-dns

---

README.md
cluster_config.yaml.example

As mentioned in #351.
There is already a note about that in the README, but I thought it might help to have it proeminently in the sample configuration as well.

Add a warning about cluster_dns and service_cidr in examples

---

README.md
docker-compose.yml

I suppose that these are obvious for someone who is familiar with Crystal; but I wasn't, and it took me a while to figure out how to build the code to test my changes :)
I've also added a working_dir to the Compose file, so that the user is placed directly in the source directory. I hope this won't affect other uses (e.g. inside VSCode).

Add build instructions

---

README.md

As requested on #355, I've added instructions about VSCode.
I had some issues running the Dev Containers extension; apparently it's not available with the open source build of VSCode; I had to install the "upstream" build and then it worked fine.

Add instructions about VSCode

---

docs/Creating_a_cluster.md

Since the main source of documentation for the configuration file format is the sample configuration, I think it's important to put a couple extra details here; namely:
- the default distro is now ubuntu-24.04
- the configuration key networking.allowed_networks.api doesn't filter access to the Kubernetes API load balancer, but to the Kubernetes API exposed on the nodes themselves
The latter is because (if I understand correctly) Hetzner load balancers don't support firewalling anyway.

Add a couple of clarifying comments in sample conf

---

src/cluster/create.cr
templates/master_install_script.sh
templates/worker_install_script.sh

Hi, sorry, 2 things in one PR. 
The cloud init improvements we discussed in #389.
BUT also: Today I get consistently timeout errors at k3s install time.
```
[Instance ax-master2] Waiting for successful ssh connectivity with instance ax-master2...
[Instance ax-master1] Instance ax-master1 already exists, skipping create
[Instance ax-master3] Instance status: running
[Instance ax-master3] Waiting for successful ssh connectivity with instance ax-master3...
[Instance ax-master1] Instance status: running
[Instance ax-master1] Waiting for successful ssh connectivity with instance ax-master1...
[Instance ax-master2] ...instance ax-master2 is now up.
[Instance ax-master2] ...instance ax-master2 created
[Instance ax-master2] ...instance ax-master2 is now up.
Error creating instance: timeout after …
```

Cloud init and Timeout from 30 to 60

---

templates/master_install_script.sh
templates/worker_install_script.sh

My erroneous brackets in the function definition are detected by the syntax checker, when applied via cloud init - and cause it to crash(!) You merged #393 yesterday and did not build a release yet, so I think not many ppl have seen it - but still:
Very sorry for that!
This is taken from cloud init output log of an autoscaler created node:
```
/var/lib/cloud/instance/scripts/runcmd: 3: update-crypto-policies: not found
/var/lib/cloud/instance/scripts/runcmd: 31: Syntax error: "(" unexpected 2024-07-31 14:05:56,542 - cc_scripts_user.py[WARNING]: Failed to run module scripts_user (scripts in /var/lib/cloud/instance/scripts) 2024-07-31 14:05:56,543 - util.py[WARNING]: Running module scripts_user (<module 'cloudinit.config.cc_scripts_user' from …
```

fix: #393 My wait function definition was buggy, causing autosc. crash

---

src/kubernetes/software/cluster_autoscaler.cr

Autoscaled nodes run the worker install script *within* cloud init itself.
There we can't wait for the file demarking finished, will never happen, since we are not finished ->
we are stuck, waiting, deadlocked.

fix: Filter cloud init wait

---

.gitignore
e2e-tests/README.md
e2e-tests/config-simple.yaml
e2e-tests/config-sshport-image.yaml
e2e-tests/env.sample
e2e-tests/list-test-results.sh
e2e-tests/run-all-tests.sh
e2e-tests/run-single-test.sh
src/hetzner/instance/create.cr

Since Ubuntu 22.10, SSH uses socket activation. This means that the SSH server isn't running by default, and gets started automatically the first time there is a connection on port 22.
Upside: it saves 3 MB of RAM.
Downside: if you're customizing the SSH port number with a drop-in configuration file at cloud-init time, it breaks SSH. SSH then needs to be restarted (or the machine needs to be rebooted) for the port number to be picked up by the systemd generator. The net result for hetzner-k3s is that if we use a non-default SSH port, provisioning breaks.
This manifests itself by the following log message:
```
systemd[1]: ssh.socket: Socket unit configuration has changed while
unit has been running, no open socket file descriptor left. The
socket unit is not functional until restarted.
``` …

Fix SSH when using non-default port

---

src/kubernetes/installer.cr

docs say # api_server_hostname: k8s.example.com # optional: DNS for the k8s API LoadBalancer. After the script has run, create a DNS record with the address of the API LoadBalancer.
And indeed, the user can't do this BEFORE running the script, not knowing the IP of the API LB created.
But since we set that hostname into the kubeconfig, when we do save_kubeconfig(master_count) and in the next command do kubectl cluster-info, this can't work - since at that time the DNS is not configured to point to that api loadbalancer.
My suggested fix is to set the IP of the LB into the kubeconfig. Then all will work and the user can, at his pace, configure his DNS to point to the api lb for that hostname - and only then adapt the kubeconfig, if wanted. SSL will work since we configure tls-sans for that …

fix: solve timeout when api server hostname is given

---

shard.lock

As noted on #309, I'm still seeing the same OpenSSL error when deploying a cluster from Fedora 40. This pull request upgrades the `crest` shard to the latest version. This fixes the deployment issue.

Upgrade `crest` shard

---

README.md
docs/Setting up a cluster.md

After many hours of staring at a 404 Not Found page from Nginx, I found there is such a thing as a "default Ingress Class".
I propose we make this part of the setup example, as the majority of the users expect this by default.
Additionally, many Helm Charts do not specify an Ingress Class, resulting in a 404 Not Found page.
(I also added a link to this setup doc, as I spent many hours today trying to get it working using snippets from issues, only to find out that there was a really nice guide hidden in the docs folder)

Nginx default ingress class

---

Dockerfile.dev

These two packages are needed to run e2e-tests inside the devcontainer.

Fix e2e-tests in devcontainer

---

src/kubernetes/software/cluster_autoscaler.cr

Hetzner started sending emails to all customers using the docker.io/hetznercloud/cluster-autoscaler images. The email reads that these images were only provided temporarily until offical releases by upstream cluster-autoscaler were ready. They ask us to start using the official images and that they will REMOVE their own images on November 19 2024.
I have tested this by rebuilding the CLI tool, creating a cluster and creating a deployment that triggered the autoscaler.

Switch to standard cluster-autoscaler image

---

docs/Setting up a cluster.md

First time to see this repo was yesterday, I WAS AMAZED, and i mean it.
now, to the issue in hand :)
the docs fixes had to be made:
- **k3s version mismatch** with the current latest version, i had a problem that every time i try to set it up with the version in docs (v1.23.3+k3s1) it would throw me a a Timeout error that i did not wrap my head around it at all, especially when i've copied everything from the docs and made the needed changes only (1+1 cluster with the types of the nodes)
also it was not related to anything with ssh as i've seen/read the issues/docs and it was not ssh or ssh-agent related stuff
- other logical docs

docs k3s version fix to latest, other docs-related fixes

---

src/configuration/settings/node_pool/location.cr

`network_zone_by_location` returns the incorrect `network_zone` for `ash`, `hil` and `sin`, preventing creation of new networks
```
[Configuration] Validating configuration...
[Configuration] ...configuration seems valid.
[Private Network] Creating private network...
[Private Network] Failed to create private network: {
"error": {
"code": "invalid_input",
"message": "invalid input in field 'subnets[0].network_zone'",
"details": {
"fields": [
{
"messages": [
"network zone does not exist"
],
"name": "subnets[0].network_zone"
}
]
}
}
}
```
See [issue](https://github.com/vitobotta/hetzner-k3s/issues/532) for more details 
I tested my change with docker compose
```
2a76b9c49fd2:/home/app/hetzner-k3s# crystal run ./src/hetzner-k3s.cr -- create --config cluster_config.yaml
_          _ …
```

Fix network_zone_by_location

---

templates/cloud_init.yaml

{{ growpart_str }}, when not empty, breaks cloud-init schema validation.
This is easily fixed by moving {{ growpart_str }} up in the template file.

fix cloud-init schema validation error when {{ growpart_str }} is not empty

---

src/configuration/networking_components/cni.cr

Was spelunking the code and found this minor mistake.

Correct error message for network encryption with disabled private network

---

.github/workflows/publish-docs.yml
Dockerfile.dev
docs/Recommendations.md
docs/Setting up a cluster.md
docs/Upgrading_a_cluster_from_1x_to_2x.md
docs/index.md
mkdocs.yml

As I am sinking into hetzner-k3s, I found navigating/searching the documentation via github itself pretty annoying, so I figured I could bootstrap docs site quickly using mkdocs
Here's how it looks: https://vvarp.github.io/hetzner-k3s/
What's done:
- basic documentation homepage, which consists of first few paragraphs of a README
- mkdocs configuration good enough to get started (with search and code highlighting enabled)
- navigation mapped to docs order as it is currently in README
- reformatted few docs to render properly in mkdocs
- added `mkdocs` to devcontainer
- github action to deploy to github pages when documentation gets updated
If you are okay to merge this, you might want to check repository configuration as mentioned at …

Set up mkdocs for documentation site

---

docs/Installation.md

This commit suggests users to define a function in their .bashrc or .zshrc to set the correct OPENSSL environment variables on Fedora.
I tested it on my machine, it works well and seems to pass the arguments correctly:

docs: add Fedora snippet to Installation.md
